# Generated by Django 2.0 on 2019-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_water', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Hot water')),
                ('cold_water', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Cold water')),
                ('electricity', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Electricity')),
                ('gaz', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Gaz')),
                ('pub_date', models.DateField(verbose_name='Publication date')),
            ],
            options={
                'db_table': 'consumption',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_water', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Hot water')),
                ('cold_water', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Cold water')),
                ('electricity', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Electricity')),
                ('gaz', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Gaz')),
                ('pub_date', models.DateField(verbose_name='Publication date')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
